Added stow colored output, and more verbose handling of stow conflicts (with colors)

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,15 +10,25 @@ IGNORE_DIRS=(
 )
 
 
-    
-RED="\033[0;31m";
-YELLOW="\033[0;33m";
-GREEN="\033[0;92m";
-CYAN="\033[0;36m";
+# ==================== COLORS ====================
+# ANSI color codes
+RED="\e[31m";
+GREEN="\e[32m";
+YELLOW="\e[33m";
+BLUE="\e[34m";
+MAGENTA="\e[35m";
+CYAN="\e[36m";
 
-BOLD="\033[1m";
-SMALL="\033[2m";
-RESET="\033[0m";
+LIGHT_RED="\e[91m";
+LIGHT_GREEN="\e[92m";
+LIGHT_YELLOW="\e[93m";
+LIGHT_BLUE="\e[94m";
+LIGHT_MAGENTA="\e[95m";
+LIGHT_CYAN="\e[96m";
+
+BOLD="\e[1m";
+SMALL="\e[2m";
+RESET="\e[0m";
 
 ARGS=("$@")
 
@@ -31,14 +41,11 @@ function check_cmds() {
     done
 };
 
-# Highlight stderr in red
-function color()(set -o pipefail;"$@" 2> >(sed $'s,.*,\e[33m&\e[m,'>&2))
-
 function log() {
     local original_args=("$@")
     [[ "$1" == "echo" ]] && shift;
 
-    printf " "
+    printf "   "
     if [[ " ${ARGS[*]} " =~ " --simulate " ]]; then
         printf "${YELLOW}"
         echo -n "$@"
@@ -52,12 +59,27 @@ function log() {
 }
 
 # Fix for stow bug
+# Apply colors to stow output
 function stow {
     local opts="-t$HOME -v  --dotfiles --ignore=install"
-    color command stow $opts "$@" 2> >(
-        sed 's/=>/->/g' |
-        grep -v 'BUG in find_stowed_path? Absolute/relative mismatch' 1>&2
-    ) 
+    command stow $opts "$@" 2> >(
+        sed '/BUG in find_stowed_path?/d' \
+        | sed 's/=>/->/g' \
+        | sed "s/^LINK\: /$(echo -e "${GREEN}   LINK: ${RESET}")/g" \
+        | sed "s/^UNLINK\: /$(echo -e "${SMALL}${GREEN} UNLINK: ${RESET}")/g" \
+        | sed "s/^WARNING\: /$(echo -e "${YELLOW}WARNING: ${RESET}")/g" \
+        | sed "s/^WARNING\! /$(echo -e "${BOLD}${RED}WARNING! ${RESET}")/g" \
+        >"$TEMP_FILE"
+    )
+    $(
+        cat "$TEMP_FILE" \
+        | sed 's/\x1b\[[0-9;]*[mGKH]//g' \
+        | rg -q 'WARNING! stowing \w* would cause conflicts'
+    ) && return 2;
+    
+    cat "$TEMP_FILE";
+    [[ $? -ne 0 ]] && return 1;
+    return 0;
 }
 
 function center() {
@@ -127,9 +149,8 @@ function main() {
     for d in "${DIRS[@]}"; do
         local dir="${d%/}"
         # Skip ignored directories
-        if [[ " ${IGNORE_DIRS[@]} " =~ " $dir " ]]; then
-            continue
-        fi
+        [[ " ${IGNORE_DIRS[@]} " =~ " $dir " ]] && continue;
+
         center '-' 40 " ${CYAN}${BOLD}$dir${RESET} ";
         
         if [[ -f "${dir}/install" ]]; then
@@ -139,16 +160,23 @@ function main() {
         fi
 
 
-        stow $@ "$dir" 2>"$TEMP_FILE"
+        stow $@ "$dir"
 
-        if grep -q "WARNING! stowing $dir would cause conflicts" "$TEMP_FILE"; then
-            local conflict_files=$(rg 'existing target is neither a link nor a directory: (\S*)' -or '$1' "$TEMP_FILE" | sort | uniq )
-            backup_files "$conflict_files" "$simulate"
-            stow "$@" "$dir" 2>"$TEMP_FILE"
-        fi
-
-        [[ $simulate == "--simulate" ]] && cat "$TEMP_FILE" >&2
-
+        case "$?" in
+            0)  echo -e "${SMALL}${BOLD}${LIGHT_GREEN}Installed $dir${RESET}";;     # TODO: fix weird coloring
+            1)  echo -e "${BOLD}${RED}Stow failed for $dir${RESET}"
+                cat "$TEMP_FILE" 
+                ;;
+            2)
+                local conflicts=$(rg 'existing target is neither a link nor a directory: (\S*)' -or '$1' "$TEMP_FILE" | sort | uniq )
+                echo -e "${BOLD}Install Conflicts:${RESET}"
+                echo -e "${SMALL}    backing up...${RESET}"
+                for c in $conflicts; do echo -e "\t${SMALL}~/$c${RESET}"; done
+                backup_files "$conflict_files" "$simulate"
+                if ! stow "$@" "$dir" && [ $simulate == "" ]; then exit -1; fi
+                ;;
+        esac
+        
     done
 }
 
