replace neofetch with fastfetch

diff --git a/packages/bash/dot-bash_profile b/packages/bash/dot-bash_profile
--- a/packages/bash/dot-bash_profile
+++ b/packages/bash/dot-bash_profile
@@ -2,17 +2,16 @@
  [[ -f ~/.bashrc ]] && source ~/.bashrc
 
 
-# Display neofetch if installed
- if ! command -v neofetch 2>&1 >/dev/null
+# Display fastfetch if installed
+ if ! command -v fastfetch 2>&1 >/dev/null
  then
-     echo "neofetch could not be found"
-     echo "sudo apt install neofetch"
+     echo "fastfetch could not be found"
+     echo "sudo apt install fastfetch"
  else
-    neofetch
+ 	fastfetch
  fi
 
 # Case-Insensitive Auto Completion
- bind "set completion-ignore-case on" 
+ bind "set completion-ignore-case on"
 
 eval "$(batman --export-env)"
-
